### ISSUE TITLE
dual-publish on apm as linter-jade

### ISSUE THREAD

**Issue by zyklus** [pugjs/pug-lint#106]
I'm the owner of `linter-jade` on apm.  I'm in the process of deleting the package there, should be gone today hopefully.  Just making a suggestion that you dual-publish this on top of that name since I don't think the naming issue is clear yet (especially on jade-lang.com)

**Comment by TimothyGu** [comment]
Is there a way to `npm deprecate` the package on apm? Sorry, I'm not real familiar with apm, but if this is the case doing that should be preferred (for compat).

**Comment by benedfit** [comment]
Closing as naming issue has cleared up with time
