### ISSUE TITLE
[Feature Request] pug-lint-loader?

### ISSUE THREAD

**Issue by jspizziri** [pugjs/pug-lint#120]
I'd love a package that would easily allow me to plug the linter into my webpack config.

Thanks!

**Comment by DevNebulae** [comment]
I support this. Even though it is not mission critical most of the time, since Pug works or it doesn't, it still makes the quality of life better since you don't have to switch between Webpack and Gulp constantly (or even the command line tool).

**Comment by Jack-Works** [comment]
@jspizziri @DevNebulae 

I just made one.
https://github.com/Jack-Works/pug-lint-loader

I'll document it later.

```Javascript
{
    test: /\.(pug|jade)$/,
    exclude: /node_modules/,
    loader: 'pug-lint-loader?' + JSON.stringify(require('./.pug-lintrc.js'))
}
```

but I think Pugjs will provide an official lint-loader in future, so I'm not publishing it to npm.
