### ISSUE TITLE
How to check multiple files?

### ISSUE THREAD

**Issue by nicothin** [pugjs/pug-lint#144]
in my `package.json`:
```
"scripts": {
    ...
    "test": "pug-lint src/**/*.pug && npm run test:style && npm run test:editorconfig && npm run build",
    ...
  },
```
but when i run the command `npm test` I see `Error: Path src/**/*.pug was not found`

![image](https://user-images.githubusercontent.com/3499680/34107239-95d0f1fa-e40c-11e7-81e8-e2d82f2045ab.png)

Tell me please, what did I do wrong?
How do I check all the files in the folder (and subfolders)?
(the pug-lint is installed locally, the global installation is not suitable)

**Comment by WilliamRADFunk** [comment]
I have the same problem. I don't believe this library supports globs.

It seems it focuses on just one file at a time, and that a separate task-runner (ie. Gulp) is needed to run pug-lint over each file in a **/*.pug glob.

I ran the same command on a single file, and it runs fine, which is why I believe it's a glob thing.

**Comment by nicothin** [comment]
strange, but it does not work for me :(
the command `ls` shows that there are *.pug files, but `glob-exec` does not "see" them.
```
nicothin@nicwin10 MINGW64 /d/projects/NTH-start-project (master)
$ npm run test:pug

> NTH-start-project@3.1.0 test:pug D:\projects\NTH-start-project
> glob-exec './src/**/*.pug' -- "ls -a ./src/ && echo files {{files.length}}"

.  ..  blocks  blocks-demo.pug  css  favicon  fonts  img  index.pug  js  pug  readme.md  scss
files 0
```
The reason is that I have windows or that I have crooked hands? ))

**Comment by qqilihq** [comment]
Sorry, didn't have any opportunity to try this on Windows yet. We're running on OS X and Linux/Docker, where it works just fine.

**Comment by rtbm** [comment]
Howdy! Windows don't like single-quoted arguments, use double, escape, enjoy.
```
{
  "scripts": {
    "lint:pug": "glob-exec \"./src/**/*.pug\" -- \"pug-lint {{files.join(' ')}}\""
  }
}
```

**Comment by nicothin** [comment]
@rtbm thank you very much!

**Comment by in-in** [comment]
It works for me without the extra asterisks
```shell
npx pug-lint -c .config/.pug-lintrc.json src
```
```shell
src/components/button/index.pug:2:1
    1| mixin button()
  > 2| 	button(class=st.btn)&attributes(attributes) foobar
-------^
    3| 

Invalid indentation

```

**Comment by Tiliavir** [comment]
I chose a slight different approach here, maybe someone finds it useful:

https://github.com/Tiliavir/mvw-creator/blob/master/ts/creator.ts, l.146
```js
export const lintPug = () => {
  Logger.info("Starting Pug Lint");

  const PugLint = require("pug-lint");
  const ConfigFile = require("pug-lint/lib/config-file");
  const linter = new PugLint();

  linter.configure(ConfigFile.load());

  return gulp.src(config.pugLintPath) // adjust accordingly
              .pipe($.data((f: File) => {
                for (const err of linter.checkPath(f.path)) {
                  Logger.warn(`${err.msg}: ${err.filename} ${err.line}:${err.column || 0}`);
                }
              }));
};
```

than i expose it to npm using (https://github.com/Tiliavir/mvw-creator/blob/master/ts/cli/lint.ts):
```js
#!/usr/bin/env node

import { lintPug } from "../creator";

lintPug();
``` 

In this specific repo I expose it in package.jsons `bin` - but you could call it in the `scripts` block as well.
