### ISSUE TITLE
Disallow id literals before class literals

### ISSUE THREAD

**Issue by brettz9** [pugjs/pug-lint#170]
With IDs providing greater specificity, it'd be nice to require that these not precede class literals. Thanks!

**Comment by BassOfBass** [comment]
Isn't there a [rule for it](https://github.com/pugjs/pug-lint/blob/master/docs/rules.md#requireclassliteralsbeforeidliterals-true) already?

**Comment by brettz9** [comment]
Hmm--am not working with Pug closely atm, but it does look like there is such a feature. Thanks!
