### ISSUE TITLE
Update README with new links to integrations

### ISSUE THREAD

**Issue by benedfit** [pugjs/pug-lint#50]
TODO:
- [x] Sublime Text 3: https://github.com/benedfit/SublimeLinter-contrib-jade-lint/issues/2
- [x] Atom: https://github.com/d9d/atom-linter-jade/issues/7
- [x] Vim: cc @benjaminparnell 
- [x] Gulp: https://github.com/emartech/gulp-jade-lint/issues/3

**Comment by benedfit** [comment]
@benjaminparnell any chance you could update syntastic to use pug-lint?

**Comment by benjaminparnell** [comment]
@benedfit yep, I will try and get it done in the next couple of days

**Comment by benjaminparnell** [comment]
@benedfit looks like someone already did it, this can be closed. https://github.com/scrooloose/syntastic/commit/ed42747560f091f083818a7e0f1b828200c9ce42
